### PR TITLE
(closes #2) Fix autotools error on travis

### LINKED ISSUE #2: Does not compile due to undocumented auto* tools
As with many projects using auto* tools this does not compile when following the instructions on

http://xchat.org/compiling/

* https://github.com/probonopd/XChat/blob/feature/app/.travis.yml
* https://travis-ci.org/probonopd/XChat/builds/303964034

Help welcome! cc @TheAssassin

### PR DESCRIPTION
**Pull request by ghost**
This fixes the current CI build but we must keep `ltmain.sh` in the repo to avoid an error in at least one auto* script.

### CODE REVIEW

**Comment by probonopd** [comment]
Thank you so very, very much @rainbru. I would not have known what to do in a hundred years. So it seems auto* just renames things and expects users to know what to do.

The AppImage is available at
https://github.com/probonopd/XChat/releases
now.

**Comment by ghost** [comment]
Yes, name changes and another macros. I wrote a blog post [autotools modernization](http://dailycommit.blogspot.fr/2017/01/how-to-modernize-your-autotools-scipts.html) some months ago.

But the main reasons of the failing CI were the missing `ltmain.sh` and the missing _autopoint_ dependency.

**Comment by probonopd** [comment]
May I ask you how you found this issue in this rather obscure project? Your PR was a real gift to me. Again, thank you.

**Comment by ghost** [comment]
I searched for [Help wanted/Good first issue](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+label%3A%22good+first+issue%22+) to help others on issue I can fix.

**Comment by probonopd** [comment]
Thank you again @rainbru, that is very kind of you. Are you aware of the [AppImage](https://appimage.org/) project? We are a very welcoming community, we think we have many great ideas but sometimes lack the knowledge and manpower to get things done, and we [could definitely use some help](https://github.com/AppImage/AppImageKit/issues?q=is%3Aissue+is%3Aopen+label%3Ahelp-wanted) from people with your kind of experience.

Our IRC channel is #AppImage on irc.freenode.net. Would appreciate to see you there.

**Pull request merged**
